name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: SiqiLu/dotnet-bump-version@master
        with:
          version_file: "MyProject/MyProject.csproj"
          version_mask: "0.0.1.0"
          version_overwrite: "*.*.*.*"
          github_token: ${{ secrets.GITHUB_TOKEN }}
