name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run scripty
        run: |
          ./ci/scripts/my-script.sh
      - name: Get tags
        run: echo "${GITHUB_REF#refs/*/}"
      - uses: SiqiLu/dotnet-bump-version@master
        with:
          version_files: "src/**/*.csproj"
          version_mask: "0.0.1.0"
          version_overwrite: "*.*.*.*"
          github_token: ${{ secrets.GITHUB_TOKEN }}
